name: CI/CD Pipeline

on:
  push:
    branches:
      - "main"  
  pull_request:
    branches:
      - "main"  

jobs:
  build-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Display Python version
      run: python --version

    - name: Set up Python environment
      run: |
        python -m venv venv
        venv\Scripts\activate  # Для Windows

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest
